// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/deco/blog.ts";
import * as $$$$$$$$$$$1 from "./apps/deco/htmx.ts";
import * as $$$$$$$$$$$2 from "./apps/site.ts";
import * as $$$$$$0 from "./sections/BlogCategories.tsx";
import * as $$$$$$1 from "./sections/BlogPost.tsx";
import * as $$$$$$2 from "./sections/BlogPosts.tsx";
import * as $$$$$$4 from "./sections/ChatSupport.tsx";
import * as $$$$$$5 from "./sections/Communications.tsx";
import * as $$$$$$3 from "./sections/CTASection.tsx";
import * as $$$$$$6 from "./sections/Faq.tsx";
import * as $$$$$$7 from "./sections/FeaturesBento.tsx";
import * as $$$$$$8 from "./sections/Footer.tsx";
import * as $$$$$$9 from "./sections/Header.tsx";
import * as $$$$$$10 from "./sections/Hero.tsx";
import * as $$$$$$11 from "./sections/IconDemo.tsx";
import * as $$$$$$12 from "./sections/ImageWithParagraph.tsx";
import * as $$$$$$13 from "./sections/Integrations.tsx";
import * as $$$$$$14 from "./sections/Logos.tsx";
import * as $$$$$$15 from "./sections/MainPost.tsx";
import * as $$$$$$16 from "./sections/Pricing.tsx";
import * as $$$$$$17 from "./sections/PrivacySecurity.tsx";
import * as $$$$$$18 from "./sections/RelatedBlogPosts.tsx";
import * as $$$$$$19 from "./sections/Statement.tsx";
import * as $$$$$$20 from "./sections/Testimonials.tsx";
import * as $$$$$$21 from "./sections/Theme/Theme.tsx";
import * as $$$$$$22 from "./sections/UseCases.tsx";
import * as $$$$$$23 from "./sections/Whitelabel.tsx";

const manifest = {
  "sections": {
    "site/sections/BlogCategories.tsx": $$$$$$0,
    "site/sections/BlogPost.tsx": $$$$$$1,
    "site/sections/BlogPosts.tsx": $$$$$$2,
    "site/sections/ChatSupport.tsx": $$$$$$4,
    "site/sections/Communications.tsx": $$$$$$5,
    "site/sections/CTASection.tsx": $$$$$$3,
    "site/sections/Faq.tsx": $$$$$$6,
    "site/sections/FeaturesBento.tsx": $$$$$$7,
    "site/sections/Footer.tsx": $$$$$$8,
    "site/sections/Header.tsx": $$$$$$9,
    "site/sections/Hero.tsx": $$$$$$10,
    "site/sections/IconDemo.tsx": $$$$$$11,
    "site/sections/ImageWithParagraph.tsx": $$$$$$12,
    "site/sections/Integrations.tsx": $$$$$$13,
    "site/sections/Logos.tsx": $$$$$$14,
    "site/sections/MainPost.tsx": $$$$$$15,
    "site/sections/Pricing.tsx": $$$$$$16,
    "site/sections/PrivacySecurity.tsx": $$$$$$17,
    "site/sections/RelatedBlogPosts.tsx": $$$$$$18,
    "site/sections/Statement.tsx": $$$$$$19,
    "site/sections/Testimonials.tsx": $$$$$$20,
    "site/sections/Theme/Theme.tsx": $$$$$$21,
    "site/sections/UseCases.tsx": $$$$$$22,
    "site/sections/Whitelabel.tsx": $$$$$$23,
  },
  "apps": {
    "site/apps/deco/blog.ts": $$$$$$$$$$$0,
    "site/apps/deco/htmx.ts": $$$$$$$$$$$1,
    "site/apps/site.ts": $$$$$$$$$$$2,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
